import {
  useEffect,
  useMemo,
  useState,
} from "react";


import {
  FiRefreshCw,
  FiSearch,
  FiFileText,
  FiDownload,
  FiPrinter,
} from "react-icons/fi";


import * as XLSX from "xlsx";

import jsPDF from "jspdf";

import autoTable from "jspdf-autotable";


import { api } from "../../services/api";




// ===============================
// Interface
// ===============================


interface Report {

  _id:string;

  title:string;

  reportType:string;

  description:string;

  generatedBy:string;

  createdAt:string;

}






const Reports =()=>{


const [
reports,
setReports
]=useState<Report[]>([]);



const [
loading,
setLoading
]=useState(false);



const [
search,
setSearch
]=useState("");



const [
type,
setType
]=useState("All");





// ===============================
// Fetch Reports
// ===============================


const fetchReports = async()=>{


try{


setLoading(true);



const response =
await api.get("/reports");



console.log(
"Reports:",
response.data
);



if(response.data?.success){


setReports(
response.data.reports || []
);


}

else if(
Array.isArray(response.data)
){


setReports(
response.data
);


}

else{


setReports([]);

}



}

catch(error){


console.error(
"Report Error:",
error
);


setReports([]);


}

finally{


setLoading(false);


}


};






useEffect(()=>{


fetchReports();


},[]);









// ===============================
// Filter
// ===============================


const filteredReports =
useMemo(()=>{


return reports.filter(
(report)=>{


const searchMatch =

report.title
?.toLowerCase()
.includes(
search.toLowerCase()
);



const typeMatch =

type==="All" ||

report.reportType===type;



return (
searchMatch &&
typeMatch
);



}

);


},[
reports,
search,
type
]);









// ===============================
// Export Excel
// ===============================


const exportExcel =()=>{


const data =
filteredReports.map(
(report)=>(

{


Title:
report.title,


Type:
report.reportType,


Description:
report.description,


GeneratedBy:
report.generatedBy,


Date:
new Date(
report.createdAt
)
.toLocaleDateString()


}

)
);



const worksheet =
XLSX.utils.json_to_sheet(
data
);



const workbook =
XLSX.utils.book_new();



XLSX.utils.book_append_sheet(
workbook,
worksheet,
"Reports"
);



XLSX.writeFile(
workbook,
"FleetDash_Reports.xlsx"
);



};









// ===============================
// Export PDF
// ===============================


const exportPDF =()=>{


const doc =
new jsPDF();



doc.text(
"FleetDash Reports",
14,
15
);



autoTable(doc,{

startY:25,


head:[

[
"Title",
"Type",
"Generated By",
"Date"
]

],


body:

filteredReports.map(
(report)=>
[

report.title,

report.reportType,

report.generatedBy,

new Date(
report.createdAt
)
.toLocaleDateString()

]

)


});



doc.save(
"FleetDash_Reports.pdf"
);


};








return (

<div className="space-y-6">





{/* HEADER */}


<div className="
flex
justify-between
items-center
">


<div>


<h1 className="
text-3xl
font-bold
text-gray-800
">

Reports

</h1>



<p className="
text-gray-500
">

Fleet analytics and reports

</p>


</div>





<button

onClick={fetchReports}

className="
bg-blue-600
hover:bg-blue-700
text-white
px-5
py-3
rounded-lg
flex
gap-2
items-center
"

>


 <FiRefreshCw
    className={
      loading
        ? "animate-spin"
        : ""
    }
  />

  Refresh

</button>

</div>










{/* KPI */}


<div className="
grid
grid-cols-1
md:grid-cols-4
gap-5
">


{
[
[
"Total Reports",
reports.length
],

[
"Daily",
reports.filter(
r=>r.reportType==="Daily"
).length
],

[
"Vehicle",
reports.filter(
r=>r.reportType==="Vehicle"
).length
],

[
"Fuel",
reports.filter(
r=>r.reportType==="Fuel"
).length
]

].map(
(item,index)=>(


<div
key={index}
className="
bg-white
shadow
rounded-xl
p-5
"
>


<p className="
text-gray-500
">

{item[0]}

</p>


<h2 className="
text-3xl
font-bold
mt-2
">

{item[1]}

</h2>


</div>


)

)

}


</div>









{/* FILTER */}


<div className="
bg-white
shadow
rounded-xl
p-5
flex
gap-4
">


<div className="
border
rounded-lg
flex
items-center
px-3
flex-1
">


<FiSearch/>


<input

className="
w-full
p-3
outline-none
"

placeholder="Search reports..."

value={search}

onChange={
e=>setSearch(
e.target.value
)
}

/>


</div>





<select

className="
border
rounded-lg
px-4
"

value={type}

onChange={
e=>setType(
e.target.value
)
}

>


<option>
All
</option>

<option>
Daily
</option>

<option>
Weekly
</option>

<option>
Monthly
</option>

<option>
Vehicle
</option>

<option>
Driver
</option>

<option>
Fuel
</option>


</select>


</div>










{/* TABLE */}


<div className="
bg-white
shadow
rounded-xl
overflow-hidden
">


<div className="
p-5
border-b
flex
justify-between
">


<h2 className="
text-xl
font-bold
flex
gap-2
items-center
">

<FiFileText/>

Reports List

</h2>




<div className="
flex
gap-3
">


<button

onClick={exportExcel}

className="
bg-green-600
text-white
px-4
py-2
rounded-lg
flex
gap-2
"

>

<FiDownload/>

Excel

</button>




<button

onClick={exportPDF}

className="
bg-red-600
text-white
px-4
py-2
rounded-lg
flex
gap-2
"

>

<FiDownload/>

PDF

</button>




<button

onClick={()=>window.print()}

className="
bg-gray-700
text-white
px-4
py-2
rounded-lg
flex
gap-2
"

>

<FiPrinter/>

Print

</button>


</div>


</div>







{
loading ?

<div className="p-6 text-center">

Loading reports...

</div>


:

filteredReports.length===0 ?


<div className="
p-6
text-center
text-gray-500
">

No Reports Found

</div>


:


<table className="
w-full
">


<thead className="
bg-gray-100
">


<tr>


<th className="p-3 text-left">
Title
</th>


<th className="p-3 text-left">
Type
</th>


<th className="p-3 text-left">
Description
</th>


<th className="p-3 text-left">
Generated By
</th>


<th className="p-3 text-left">
Date
</th>


</tr>


</thead>



<tbody>


{
filteredReports.map(
(report)=>(


<tr
key={report._id}
className="
border-t
hover:bg-gray-50
"
>


<td className="p-3 font-semibold">

{report.title}

</td>



<td className="p-3">

{report.reportType}

</td>



<td className="p-3">

{report.description}

</td>



<td className="p-3">

{report.generatedBy}

</td>



<td className="p-3">

{
new Date(
report.createdAt
)
.toLocaleDateString()
}

</td>



</tr>


)

)

}


</tbody>


</table>


}


</div>




</div>


);


};



export default Reports;